spec:
  replicas: 1
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.2"
              memory: 1.5G
            limits:
              cpu: "1.0"
              memory: 2G
          env:
          - name: MYSQL_SERVICE_NAME
            value: mysql
          - name: MYSQL_SERVICE_DATABASE
            value: sampledb
          - name: MYSQL_SERVICE_USERNAME
            value:
          - name: MYSQL_SERVICE_PASSWORD
            value: