apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migration
spec:
  template:
    metadata:
      name: kong-migration
    spec:
      containers:
      - name: kong-migration
        image: kong
        env:
          - name: KONG_NGINX_DAEMON
            value: 'off'
          - name: KONG_PG_USER
            value: kong
          - name: KONG_PG_PASSWORD
            value: "kong"
          - name: KONG_PG_DATABASE
            value: 'kong'
          - name: KONG_PG_HOST
            value: kong-databases.svc.cluster.local
        command: [ "/bin/sh", "-c", "kong migrations up" ]
      restartPolicy: Never